var activities = [
  { description: 'Fly a kite'},
  { description: 'Pancake art'},
  { description: 'Go to the roller rink'},
  { description: 'Make a homemade pizza'},
  { description: 'Make a marshmallow catapult'},
  { description: 'Tennis at the local park'},
  { description: 'Drive in movie!'},
  { description: 'Color!'},
  { description: 'Do a jigsaw puzzle'},
  { description: 'Sing in the rain'},
  { description: 'Write a letter to a friend'},
  { description: 'Be a tourist in your own city!'},
  { description: 'Do the macarena'},
  { description: 'PILLOW FIGHT!'},
  { description: 'Make a fort'},
  { description: 'Star Wars marathon!'},
  { description: 'Zoo'},
  { description: 'Playground!'},
  { description: 'Have a paper airplane contest'},
  { description: 'Have a water balloon fight'},
  { description: 'Go biking!'},
  { description: 'Pretend to be a pirate for a day'},
  { description: 'Mini-golf!'},
  { description: 'Catch fireflies'},
  { description: 'Stay at home dance party!'}];